version: '3'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ../Dockerfile.eureka-server
    ports:
      - "8761:8761"

  book-client:
    build:
      context: ./book-client
      dockerfile: ../Dockerfile.book-client
    ports:
      - "80"
    depends_on:
      - eureka-server

  customer-client:
    build:
      context: ./customer-client
      dockerfile: ../Dockerfile.customer-client
    ports:
      - "80"
    depends_on:
      - eureka-server

