version: '3'
services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile.eureka-server
    ports:
      - "8761:8761"

  eureka-client:
    build:
      context: .
      dockerfile: book-client/Dockerfile.book-client
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
