version: '3'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile.eureka-server
    ports:
      - "8761:8761"

  eureka-client:
    build:
      context: ./book-client
      dockerfile: Dockerfile.eureka-client
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
